name: testing-workflow
run-name: Unit tests with Swift 6 started by ${{ github.actor }}
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tomieq/food_test:1.0 -f TestDockerfile .
      - run: docker run --rm -v "$PWD:/code" -w /code tomieq/food_test:1.0 swift test
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tomieq/food_blog:1.0 .